//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by KaiUI.rc
//
#define ID_REPLACE_ALL                  101
#define ID_CLOSE                        102
#define IDD_ABOUTBOX                    103
#define IDR_MAINFRAME                   104
#define IDR_KAITYPE                     105
#define IDS_LINE_SPACING_AUTO           106
#define IDS_LINE_SPACING_SINGLE         107
#define IDD_TRACE_WINDOW                108
#define IDS_LINE_SPACING_1_5            109
#define IDS_LINE_SPACING_DOUBLE         110
#define IDS_LINE_SPACING_EXACT          111
#define IDS_LINE_SPACING_MULTIPLE       112
#define ID_FORMAT_PARAGRAPH             113
#define ID_INSERT_DIACRITICS            114
#define ID_EDIT_DELETE                  115
#define IDR_WATERMARK                   116
#define ID_Menu                         117
#define IDS_ALIGNMENT_LEFT              118
#define ID_EDIT_FINDANDREPLACE          119
#define IDS_ALIGNMENT_RIGHT_JUSTIFY     120
#define ID_FINDANDREPLACE_FIND          121
#define ID_FINDANDREPLACE_REPLACE       122
#define IDD_SEARCH_DLG                  123
#define IDS_ALIGNMENT_CENTER            124
#define IDS_ALIGNMENT_RIGHT             125
#define IDR_CONTEXT                     126
#define IDD_FORMAT_PARAGRAPH            127
#define IDD_SELECT_LANGUAGE_DLG         151
#define IDD_DIALOG1                     152
#define IDD_KAI_FONT_DIALOG             152
#define IDI_ICON1                       164
#define IDI_ICON2                       178
#define IDI_ICON3                       183
#define IDC_TRACE_EDIT                  1000
#define READ_ERROR                      1001
#define READ_ERROR_VERSION              1002
#define READ_ERROR_WATERMARK            1003
#define WRITE_ERROR                     1004
#define IMPORT_ERROR_SEEK               1011
#define IMPORT_ERROR_READ               1014
#define REG_ERROR_OPENKEY               1021
#define REG_ERROR_ENUMKEY               1022
#define REG_ERROR_QUERYKEY              1023
#define REG_ERROR_SETVALUE              1024
#define REG_ERROR_CREATEKEY             1025
#define REG_ERROR_KEY_EXISTS            1026
#define ID_REPLACE                      1040
#define ID_NEXT                         1041
#define IDC_LANGUAGE_COMBO              1055
#define IDC_CAPTION                     1056
#define IDC_STATIC_VERSION              1057
#define IDC_STATIC_COPYRIGHT            1058
#define IDC_STATIC_VERSION2             1059
#define IDC_STATIC_BUILD                1059
#define MISC_ERROR_BAD_TIME_STR         1101
#define MISC_ERROR_LOGFILE_CREATE       1102
#define IDC_CHECK_MATCH_WHOLE_WORD      2002
#define IDC_CHECK_MATCH_CASE            2003
#define IDC_CHECK_IGNORE_DIACRITICS     2004
#define IDC_RADIO_UP                    2005
#define IDC_RADIODOWN                   2006
#define IDC_RADIO_DOWN                  2006
#define IDC_CHECK_BOOLEAN_SEARCH        2007
#define IDC_CHECK_REGEX                 2008
#define IDC_COMBO_FIND_WHAT             2010
#define IDC_COMBO_REPLACE_WITH          2012
#define IDC_BUTTON_AND                  2019
#define IDC_BUTTON_OR                   2020
#define IDC_BUTTON_NOT                  2021
#define IDC_RIGHT_INDENT_EDIT           2022
#define IDC_BUTTON_LP                   2024
#define IDC_BUTTON_RP                   2025
#define IDC_STATIC_BOOL                 2026
#define IDC_BUTTON_CLEAR                2027
#define IDC_BUTTON_BOOLSEARCH           2028
#define IDC_STATIC_SEPARATOR            2029
#define IDC_STATIC_FIND_WHAT            2030
#define IDC_STATIC_ENTER_TERM           2031
#define IDC_STATIC_REPLACE_WITH         2031
#define IDC_EDIT_ENTER_TERM             2032
#define IDC_BUTTON_START_OVER           2033
#define IDC_PROXIMITY_COMBO             2034
#define IDC_RADIO_PROXIMITY_WORDS       2035
#define IDC_RADIO_PROXIMITY_SENTENCES   2036
#define IDC_RADIO_PROXIMITY_PARAGRAPHS  2037
#define IDC_STATIC_WITHIN               2038
#define IDC_PROXIMITY_GROUP_STATIC      2039
#define IDC_STATIC_DIRECTION            2041
#define IDC_ALIGNMENT_COMBO             2043
#define IDC_LEFT_INDENT_COMBO           2044
#define IDC_RIGHT_INDENT_COMBO          2045
#define IDC_SPIN                        2049
#define IDC_LINE_SPACE_SPIN             2049
#define IDC_LINE_SPACE_EDIT             2050
#define IDC_LEFT_INDENT_EDIT            2051
#define IDC_LEFT_INDENT_SPIN            2052
#define IDC_RIGHT_INDENT_SPIN           2053
#define IDC_LINE_SPACE_COMBO            2054
#define ID_SCROLL_TO_BOTTOM             32771
#define ID_SCROLL_TO_TOP                32772
#define ID_PGDN                         32773
#define ID_PGUP                         32774
#define ID_SELECT_TO_TOP                32775
#define ID_SELECT_TO_BOTTOM             32776
#define ID_SELECT_PGDN                  32777
#define ID_LEFT                         32778
#define ID_HOME                         32779
#define ID_END                          32780
#define ID_RIGHT                        32781
#define ID_UP                           32782
#define ID_DOWN                         32783
#define ID_DELETE                       32784
#define ID_BACK                         32785
#define ID_SELECT_RIGHT                 32786
#define ID_SELECT_LEFT                  32788
#define ID_SELECT_TO_END                32792
#define ID_SELECT_TO_HOME               32794
#define ID_SELECT_UP                    32799
#define ID_SELECT_DOWN                  32800
#define ID_WORD_RIGHT                   32804
#define ID_WORD_LEFT                    32805
#define ID_CONTEXT_COPY                 32807
#define ID_CONTEXT_PASTE                32808
#define ID_CONTEXT_PARAGRAPH            32809
#define ID_CONTEXT_CUT                  32811
#define ID_TO_BOLD                      32812
#define ID_TO_ITALIC                    32813
#define ID_TO_UNDERLINE                 32814
#define ID_INSERT_DIACRITIC             32816
#define ID_INSERT_DIACRITIC_KEY         32816
#define ID_INSERT_DIACRITIC_MENU        32818
#define ID_TOOLS_TRANSCRIBE             32819
#define ID_TOOLS_ACCENTUATE             32820
#define ID_TOOLS_ASCIIDECODER           32821
#define ID_TOOLS_ASCIIDECODER_VIEW      32822
#define ID_INDICATOR_PROGRESS           59142
#define ID_TOGGLE_INSERT                61446

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32823
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
