//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Kai.rc
//
#define IDCANCEL2                       5
#define ID_REPLACE_ALL                  5
#define IDCANCEL3                       6
#define ID_CLOSE                        6
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_KAITYPE                     129
#define IDD_TRACE_WINDOW                132
#define ID_FORMAT_PARAGRAPH             136
#define ID_INSERT_DIACRITICS            137
#define ID_EDIT_DELETE                  138
#define IDR_WATERMARK                   139
#define ID_Menu                         139
#define ID_EDIT_FINDANDREPLACE          141
#define ID_FINDANDREPLACE_FIND          142
#define ID_FINDANDREPLACE_REPLACE       143
#define IDD_SEARCH_DLG                  144
#define IDR_CONTEXT                     147
#define IDD_FORMAT_PARAGRAPH            149
#define IDC_EDIT1                       1000
#define READ_ERROR                      1001
#define IDC_LIST1                       1001
#define READ_ERROR_VERSION              1002
#define IDC_CHECK_MATCH_WHOLE_WORD      1002
#define READ_ERROR_WATERMARK            1003
#define IDC_CHECK_MATCH_CASE            1003
#define WRITE_ERROR                     1004
#define IDC_CHECK_IGNORE_DIACRITICS     1004
#define IDC_RADIO_UP                    1005
#define IDC_RADIODOWN                   1006
#define IDC_RADIO_DOWN                  1006
#define IDC_CHECK_BOOLEAN_SEARCH        1007
#define IDC_CHECK_REGEX                 1008
#define IDC_COMBO_FIND_WHAT             1010
#define IMPORT_ERROR_SEEK               1011
#define IDC_COMBO_REPLACE_WITH          1012
#define IMPORT_ERROR_READ               1014
#define IDC_BUTTON_AND                  1019
#define IDC_BUTTON_OR                   1020
#define REG_ERROR_OPENKEY               1021
#define IDC_BUTTON_NOT                  1021
#define REG_ERROR_ENUMKEY               1022
#define IDC_EDIT2                       1022
#define REG_ERROR_QUERYKEY              1023
#define IDC_BUTTON4                     1023
#define REG_ERROR_SETVALUE              1024
#define IDC_BUTTON5                     1024
#define IDC_BUTTON_LP                   1024
#define REG_ERROR_CREATEKEY             1025
#define IDC_BUTTON_RP                   1025
#define REG_ERROR_KEY_EXISTS            1026
#define IDC_STATIC_BOOL                 1026
#define IDC_BUTTON_CLEAR                1027
#define IDC_BUTTON_BOOLSEARCH           1028
#define IDC_STATIC_SEPARATOR            1029
#define IDC_STATIC_FIND_WHAT            1030
#define IDC_STATIC_ENTER_TERM           1031
#define IDC_STATIC_REPLACE_WITH         1031
#define IDC_EDIT_ENTER_TERM             1032
#define IDC_BUTTON_START_OVER           1033
#define IDC_PROXIMITY_COMBO             1034
#define IDC_RADIO_PROXIMITY_WORDS       1035
#define IDC_RADIO_PROXIMITY_SENTENCES   1036
#define IDC_RADIO_PROXIMITY_PARAGRAPHS  1037
#define IDC_STATIC_WITHIN               1038
#define IDC_PROXIMITY_GROUP_STATIC      1039
#define ID_REPLACE                      1040
#define ID_NEXT                         1041
#define IDC_STATIC_DIRECTION            1041
#define IDC_COMBO1                      1043
#define IDC_COMBO2                      1044
#define IDC_COMBO3                      1045
#define IDC_SPIN2                       1049
#define IDC_SPIN                        1049
#define MISC_ERROR_BAD_TIME_STR         1101
#define MISC_ERROR_LOGFILE_CREATE       1102
#define ID_SCROLL_TO_BOTTOM             32771
#define ID_SCROLL_TO_TOP                32772
#define ID_PGDN                         32773
#define ID_PGUP                         32774
#define ID_SELECT_TO_TOP                32775
#define ID_SELECT_TO_BOTTOM             32776
#define ID_SELECT_PGDN                  32777
#define ID_LEFT                         32778
#define ID_HOME                         32779
#define ID_END                          32780
#define ID_RIGHT                        32781
#define ID_UP                           32782
#define ID_DOWN                         32783
#define ID_DELETE                       32784
#define ID_BACK                         32785
#define ID_SELECT_RIGHT                 32786
#define ID_SELECT_LEFT                  32788
#define ID_SELECT_TO_END                32792
#define ID_SELECT_TO_HOME               32794
#define ID_SELECT_UP                    32799
#define ID_SELECT_DOWN                  32800
#define ID_WORD_RIGHT                   32804
#define ID_WORD_LEFT                    32805
#define ID_CONTEXT_COPY                 32807
#define ID_CONTEXT_PASTE                32808
#define ID_CONTEXT_PARAGRAPH            32809
#define ID_CONTEXT_CUT                  32811
#define ID_TOGGLE_INSERT                61446

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
